name: SDF Validation
run-name: validate
on:
  push:
    branches: [main, articles/*]
jobs:
  sdf-deploy:
    runs-on: ubuntu-latest
    environment: ${{ github.ref_name == 'main' && 'production' || 'sandbox' }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '18'
      - name: Install dependencies
        run: |
          npm install @oracle/suitecloud-cli@2.0.0 --no-package-lock --save-dev --legacy-peer-deps --acceptsuitecloudsdklicense
      - name: Setup private key
        run: |
          echo "${{ secrets.NS_PRIVATE_KEY }}" > private-key.pem
          chmod 600 private-key.pem
      - name: Setup Project Account
        env:
          NS_ACCOUNT: ${{ secrets.NS_ACCOUNT_ID }}
          NS_CERT_ID: ${{ secrets.NS_CERT_ID }}
        run: |
          ./node_modules/.bin/suitecloud account:setup:ci --account "$NS_ACCOUNT" --authid "production_root" --certificateid "$NS_CERT_ID" --privatekeypath "./private-key.pem"
      - name: Initialize SuiteCloud Project
        env:
          NS_ACCOUNT: ${{ secrets.NS_ACCOUNT_ID }}
          NS_CERT_ID: ${{ secrets.NS_CERT_ID }}
        run: |
          ./node_modules/.bin/suitecloud project:create --projectname netsuite-deployment --projectversion 1.0.0 --type ACCOUNTCUSTOMIZATION --overwrite
          cd netsuite-deployment
          ../node_modules/.bin/suitecloud account:setup:ci --account "$NS_ACCOUNT" --authid "production_deploy" --certificateid "$NS_CERT_ID" --privatekeypath "../private-key.pem"
      - name: Deploy file
        run: |
          pwd
          ls -la src/FileCabinet/SuiteScripts/
          ./node_modules/.bin/suitecloud file:upload --paths "./src/FileCabinet/SuiteScripts/ctc_test_script_vcs1.js,/SuiteScripts/ctc_test_script_vcs1.js"
  sdf-validate:
    runs-on: ubuntu-latest
    environment: ${{ github.ref_name == 'main' && 'production' || 'sandbox' }}
    needs: sdf-deploy
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '18'
      - name: Install dependencies
        run: |
          npm install @oracle/suitecloud-cli@2.0.0 --no-package-lock --save-dev --legacy-peer-deps --acceptsuitecloudsdklicense
      - name: Setup private key
        run: |
          echo "${{ secrets.NS_PRIVATE_KEY }}" > private-key.pem
          chmod 600 private-key.pem
      - name: Setup Project Account
        env:
          NS_ACCOUNT: ${{ secrets.NS_ACCOUNT_ID }}
          NS_CERT_ID: ${{ secrets.NS_CERT_ID }}
        run: |
          ./node_modules/.bin/suitecloud account:setup:ci --account "$NS_ACCOUNT" --authid "production" --certificateid "$NS_CERT_ID" --privatekeypath "./private-key.pem"
      - name: Initialize SuiteCloud Project
        run: |
          ./node_modules/.bin/suitecloud project:create --projectname netsuite-validation --projectversion 1.0.0 --overwrite
      - name: Validate project
        run: npm run validate