name: SDF Validation
run-name: validate
on:
  push:
    branches: [main, articles/*]
jobs:
  sdf-deploy:
    runs-on: ubuntu-latest
    environment: ${{ github.ref_name == 'main' && 'production' || 'sandbox' }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '16'
      - uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'oracle'
      - name: Install dependencies
        run: |
          npm config set @oracle/suitecloud-cli:acceptSuiteCloudSDKLicense true
          npm install --no-package-lock
      - name: Authenticate with NetSuite
        run: ./node_modules/.bin/suitecloud account:savetoken --account ${{ vars.NS_ACCOUNT_ID }} --authid ${{ vars.NS_ACCOUNT_ID }} --tokenid ${{ secrets.NS_TOKEN_ID }} --tokensecret ${{ secrets.NS_TOKEN_SECRET }}
      - name: Deploy project
        run: npm run deploy
  sdf-validate:
    runs-on: ubuntu-latest
    environment: ${{ github.ref_name == 'main' && 'production' || 'sandbox' }}
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/sdf-install
        with:
          ns-account-id: ${{ vars.NS_ACCOUNT_ID }}
          ns-token-id: ${{ secrets.NS_TOKEN_ID }}
          ns-token-secret: ${{ secrets.NS_TOKEN_SECRET }}
      - name: Validate project against ${{ vars.NS_ACCOUNT_ID }}
        run: npm run validate
  unit-test:
    runs-on: ubuntu-latest
    environment: ${{ github.ref_name == 'main' && 'production' || 'sandbox' }}
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/sdf-install
        with:
          ns-account-id: ${{ vars.NS_ACCOUNT_ID }}
          ns-token-id: ${{ secrets.NS_TOKEN_ID }}
          ns-token-secret: ${{ secrets.NS_TOKEN_SECRET }}
      - name: Run unit tests
        run: npm test
