name: SDF Validation
run-name: validate
on:
  push:
    branches: [main, articles/*]
jobs:
  sdf-deploy:
    runs-on: ubuntu-latest
    environment: ${{ github.ref_name == 'main' && 'production' || 'sandbox' }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '18'
      - name: Install dependencies
        run: |
          npm install @oracle/suitecloud-cli@2.0.0 --no-package-lock --save-dev --legacy-peer-deps --acceptsuitecloudsdklicense
      - name: Setup private key
        run: |
          echo "${{ secrets.NS_PRIVATE_KEY }}" > private-key.pem
          chmod 600 private-key.pem
      - name: Setup Project Account
        env:
          NS_ACCOUNT: ${{ secrets.NS_ACCOUNT_ID }}
          NS_CERT_ID: ${{ secrets.NS_CERT_ID }}
        run: |
          ./node_modules/.bin/suitecloud account:setup:ci --account "$NS_ACCOUNT" --authid "production" --certificateid "$NS_CERT_ID" --privatekeypath "./private-key.pem"
      - name: Verify directory exists
        run: |
          mkdir -p src/FileCabinet/SuiteScripts
      - name: Debug file paths
        run: |
          echo "Current directory:"
          pwd
          echo "Files in SuiteScripts:"
          ls -la src/FileCabinet/SuiteScripts/
          echo "Testing file path:"
          test -f "src/FileCabinet/SuiteScripts/test_2.js" && echo "File exists" || echo "File not found"
      - name: Debug file paths
        run: |
          echo "Current directory:"
          pwd
          echo "Files in SuiteScripts:"
          ls -la src/FileCabinet/SuiteScripts/
          echo "File content:"
          cat src/FileCabinet/SuiteScripts/ctc_test_script_vcs1.js

      - name: Deploy single file
        run: |
          ./node_modules/.bin/suitecloud file:upload --paths "$WORKSPACE_PATH/src/FileCabinet/SuiteScripts/ctc_test_script_vcs1.js","
      - name: Debug paths
        run: |
          WORKSPACE_PATH=$(pwd)
          echo "Source path: $WORKSPACE_PATH/src/FileCabinet/SuiteScripts/ctc_test_script_vcs1.js"
          echo "Full command: ./node_modules/.bin/suitecloud file:upload --paths \"$WORKSPACE_PATH/src/FileCabinet/SuiteScripts/ctc_test_script_vcs1.js,/SuiteScripts/ctc_test_script_vcs1.js\""
      - name: Deploy project
        run: |
          WORKSPACE_PATH=$(pwd)
          ./node_modules/.bin/suitecloud file:upload --paths "$WORKSPACE_PATH/src/FileCabinet/SuiteScripts/ctc_test_script_vcs1.js,/SuiteScripts/ctc_test_script_vcs1.js"

  sdf-validate:
    runs-on: ubuntu-latest
    environment: ${{ github.ref_name == 'main' && 'production' || 'sandbox' }}
    needs: sdf-deploy
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '18'
      - name: Install dependencies
        run: |
          npm install @oracle/suitecloud-cli@2.0.0 --no-package-lock --save-dev --legacy-peer-deps --acceptsuitecloudsdklicense
      - name: Setup private key
        run: |
          echo "${{ secrets.NS_PRIVATE_KEY }}" > private-key.pem
          chmod 600 private-key.pem
      - name: Setup Project Account
        env:
          NS_ACCOUNT: ${{ secrets.NS_ACCOUNT_ID }}
          NS_CERT_ID: ${{ secrets.NS_CERT_ID }}
        run: |
          ./node_modules/.bin/suitecloud account:setup:ci --account "$NS_ACCOUNT" --authid "production" --certificateid "$NS_CERT_ID" --privatekeypath "./private-key.pem"
      - name: Validate project
        run: npm run validate