name: SDF Validation
run-name: validate
on:
  push:
    branches: [main, articles/*]
jobs:
  sdf-deploy:
    runs-on: ubuntu-latest
    environment: ${{ github.ref_name == 'main' && 'production' || 'sandbox' }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '18'
      - uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'oracle'
      - name: Install dependencies
        run: |
          npm install @oracle/suitecloud-cli@2.0.0 --no-package-lock --save-dev --legacy-peer-deps --acceptsuitecloudsdklicense
      - name: Authenticate with NetSuite
        env:
          NS_ACCOUNT: ${{ secrets.NS_ACCOUNT_ID }}
          NS_TOKEN_ID: ${{ secrets.NS_TOKEN_ID }}
          NS_TOKEN_SECRET: ${{ secrets.NS_TOKEN_SECRET }}
        run: ./node_modules/.bin/suitecloud account:savetoken --account "$NS_ACCOUNT" --tokenid "$NS_TOKEN_ID" --tokensecret "$NS_TOKEN_SECRET"
      - name: Deploy project
        run: npm run deploy
  sdf-validate:
    runs-on: ubuntu-latest
    environment: ${{ github.ref_name == 'main' && 'production' || 'sandbox' }}
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/sdf-install
        with:
          ns-account-id: ${{ secrets.NS_ACCOUNT_ID }}nb
          ns-token-id: ${{ secrets.NS_TOKEN_ID }}
          ns-token-secret: ${{ secrets.NS_TOKEN_SECRET }}
      - name: Authenticate with NetSuite
        env:
          NS_ACCOUNT: ${{ secrets.NS_ACCOUNT_ID }}
          NS_TOKEN_ID: ${{ secrets.NS_TOKEN_ID }}
          NS_TOKEN_SECRET: ${{ secrets.NS_TOKEN_SECRET }}
        run: ./node_modules/.bin/suitecloud account:savetoken --account "$NS_ACCOUNT" --tokenid "$NS_TOKEN_ID" --tokensecret "$NS_TOKEN_SECRET"
      - name: Validate project against ${{ secrets.NS_ACCOUNT_ID }}
        run: npm run validate